# Generated by Django 3.2.15 on 2022-09-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_filer',
            new_name='image_filter',
        ),
    ]
